### ISSUE TITLE
[BUG] matching on root entries

### ISSUE THREAD

**Issue by mindreframer** [hrzndhrn/glob_ex#1]
Hi @NickNeck, thanks for this good looking library! 

Going to the root folder `/` and trying following code I've noticed a bug: 

```elixir

Path.wildcard("Users/*")
=> ["Users/Shared", "Users/demo", "Users/roman"]


GlobEx.match?(~g|Users/*|, "Users/roman")
=> true


Path.wildcard("/Users/*")
=> ["/Users/Shared", "/Users/demo", "/Users/roman"]


GlobEx.match?(~g|/Users/*|, "/Users/roman")
=> false
```

This was tripping me up when trying to match paths that start with `/` ... It always came back empty. 

Maybe the fix is not soo hard? If you dont have time, I might look into it. 

Have a good weekend!
Roman

**Comment by mindreframer** [comment]
Hi, I've tried tracing it and it looks like this: 

```elixir
Interactive Elixir (1.14.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :dbg.start
{:ok, #PID<0.281.0>}
iex(2)> :dbg.tracer(:process, {fn _, 5 -> :dbg.stop_clear()
...(2)>                         msg, n -> IO.inspect(msg); n+1 end, 0})
{:ok, #PID<0.281.0>}
iex(3)>
nil
iex(4)> :dbg.tpl(GlobEx, :match?, [])
{:ok, [{:matched, :nonode@nohost, 2}]}
iex(5)> :dbg.p(:all, :c)
{:ok, [{:matched, :nonode@nohost, 121}]}
iex(6)> import GlobEx.Sigils
GlobEx.Sigils
iex(7)> GlobEx.match?(~g|/Users/*|, "/Users/user")
{:trace, #PID<0.279.0>, :call, {GlobEx, :match?, [~g|/Users/*|, "/Users/user"]}}
{:trace, #PID<0.279.0>, :call,
 {GlobEx, :match?, [[{:exact, '/Users'}, :star], false, [[], 'sresU', 'resu']]}}
false
```

**Comment by NickNeck** [comment]
Good catch. Thanks for reporting.

**Comment by mindreframer** [comment]
@NickNeck Wow, thanks for the fix! It looks really elegant, I was messing with the compiler by reversing the path concatenation in the add {:exact} function clause: 
- https://github.com/hrzndhrn/glob_ex/blob/main/lib/glob_ex/compiler.ex#L236

That was slightly helping, but the case where folder ".foo" should match ".foo" matcher _WITHOUT_ `match_dot` option was screwing my mind. 

Thanks again!
