### ISSUE TITLE
[BUG] matching on pattern starting with slash and having more than 2 path segments

### ISSUE THREAD

**Issue by mindreframer** [hrzndhrn/glob_ex#3]
Hey @NickNeck, it seems there is still one corner-case, that fails to match with `/`-starting paths. I hope this is the last one :) 

```elixir
import GlobEx.Sigils
GlobEx.match?(~g|/a/b/**|d, "/a/b/c")
# => false

GlobEx.match?(~g|/a/**|d, "/a/c")
# => true
```

**Comment by NickNeck** [comment]
Sorry for that and thanks for reporting. I will take a look.

**Comment by mindreframer** [comment]
@NickNeck thanks!

**Comment by NickNeck** [comment]
@mindreframer that was a big bug. Thanks for this catch. The fix is in the `main` branch. If you like you can test it with the `main` branch. I will add a little refactoring at the weekend and release a new version.

**Comment by mindreframer** [comment]
@NickNeck Thanks! I'll try it a bit later, but from the the ex_unit test assertions it should cover my needs fully. And I see you moved away from the path concatenation in the exact match, this was also my hunch initially. Just couldn't figure out the full picture :) Looking forward to use glob_ex!

**Comment by NickNeck** [comment]
@mindreframer version 0.1.3 is released.
